// export { default as TableRenderer } from './TableRenderer.vue'
export { default as TableRenderer } from './TableRenderer.jsx'
export { default as TSVRenderer } from './TSVRenderer.jsx'
export { default as createPlotlyRenderer } from './PlotlyRenderer.jsx'
export { default as createChartjsRenderer } from './ChartjsRenderer.jsx'
export { default as FoobarRenderer } from './FoobarRenderer.jsx'
export { default as TestRenderer } from './TestRenderer.jsx'
